FROM golang:1.21-alpine AS builder

ENV CGO_ENABLED=0
ARG GOOS=linux
ARG GOARCH=amd64

ARG COMMIT_HASH=NOT_SET
ARG GIT_BRANCH=NOT_SET
ARG BUILD_TIMESTAMP=NOT_SET
ARG VERSION=NOT_SET

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -ldflags="-w -s -extldflags= \
  -X 'github.com/mogenius/punq/version.GitCommitHash=${COMMIT_HASH}' \
  -X 'github.com/mogenius/punq/version.Branch=${GIT_BRANCH}' \
  -X 'github.com/mogenius/punq/version.BuildTimestamp=${BUILD_TIMESTAMP}' \
  -X 'github.com/mogenius/punq/version.Ver=${VERSION}'" -o bin/punq-operator .


FROM alpine:latest

RUN apk add --no-cache curl bash

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$GOARCH/kubectl"
RUN chmod +x kubectl
RUN mv kubectl /usr/local/bin/kubectl

WORKDIR /app

COPY --from=builder ["/app/bin/punq-operator", "."]
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENV GIN_MODE=release

ENTRYPOINT [ "/app/punq-operator", "operator" ]